// VARIABALEE IN JAVA SCRIPT : 1-LET 2-VAR 3-CONST # AUTOMATICALLY
const accountId = 2005;
let accountEmail = "raj123@.com";
var accountPassword = "12345";
accountCity = "Jabalpur";
let accountState;

// // IN CONST VARIABLE:
// accountId=2006;
// console.log(accountId);

//  ANS-Assignment to constant variable.-IN TERMS OF NORMAL LANGUAGE WE CAN NOT CHANGE THE VALUE OF accountId RESON IS accountId IS ASIGN WITH CONST VARIABLE

accountEmail = "gsvks"
accountPassword = "21212121"
accountCity = "jaipur"

console.log(accountEmail);
console.log(accountPassword);
console.log(accountCity);

// ANOTHER VARIABLE VALEUE IS EASILY CHANGED:

// DIFFERENCE BETWEEN LET AND VAR VARIABLE
//  LET KEYWORD:--The let keyword was introduced in ES6 (2015)

//  1-Variables declared with let have Block Scope
// 2-Variables declared with let must be Declared before use
// 3_Variables declared with let cannot be Redeclared in the same scope

//   let raj=raj;
// undefined
// raj
// 'raj'
// let raj=rishi
// VM805:1 Uncaught ReferenceError: rishi is not defined
//     at <anonymous>:1:9**

//   VAR KEYWORD:

//<--// Variables defined with var can be redeclared. you can redeclare var in same scop;

// With var you can do this:

//{var x = "John Doe";

// var x = 0;-->**}










