// DATA TYPES IN JAVA SCRIPT: 1-PRIMITIVE 2-NON-PRIMITIVE


// number => 2 to power 53 /// TYPE NUMBER
let raj=41;
console.log(typeof(raj));

// bigint = 4566789899086544// TYPE UNDEFINED

// string => "" //STRING
let d1="raj"
console.log(typeof(d1));

// boolean => true/false //TYPE BOOLEAN
let d2= true;
console.log(typeof(d2));

// null => standalone value // TYPE "OBJECT"
let r =null;
console.log(typeof(r));// object


// undefined =>  value is not asign
let d4;
console.log(typeof(d4));

// symbol => unique

// object

console.log(typeof undefined); // undefined

// ****************** DATA TYPES IN BRIEF***********

//  Primitive

//  7 types : String, Number, Boolearn, null, undefined, Symbol, BigInt

const score = 100
const scoreValue = 100.3

const isLoggedIn = false
const outsideTemp = null
let userEmail;

const id = Symbol('123')
const anotherId = Symbol('123')

console.log(id === anotherId);

// const bigNumber = 3456543576654356754n//TYPE UNDE



// Reference (Non primitive)

// Array, Objects, Functions

const heros = ["shaktiman", "naagraj", "doga"];
let myObj = {
    name: "hitesh",
    age: 22,
}

const myFunction = function(){
    console.log("Hello world");
}

console.log(typeof anotherId);

// BASIC OVER VIEW