//CONCEPT OF DATE AND TIME:
let myDate = new Date();
console.log(myDate);//2024-11-22T11:14:54.432Z IT IS OUTPUT
console.log(myDate.toDateString());//Fri Nov 22 2024

console.log(myDate.toLocaleString());//
// 22/11/2024, 4:46:47 pm

console.log(typeof( myDate));//object


let myCreatedDate=new Date(2023,0,23);
// console.log(myCreatedDate);

console.log(myCreatedDate.toDateString());//Mon Jan 23 2023 

// ****NOTE:MONTHS START IN JAVA SCRIPT IN 0*****



l

